FROM node:9.4.0-alpine as builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
USER root

COPY package.json /usr/src/app/
RUN npm install

COPY . .

RUN npm run build:prod


FROM nginx

WORKDIR /usr/share/nginx/html/

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/dist  /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
