version: '3.5'

services:
  hovi-web_build:
    build: ../
    container_name: 'hovi-web_build'
    command: npm run build:prod
    volumes:
      - dist:/usr/src/app/dist

  hovi-web_nginx:
    image: nginx
    ports:
      - 80:80
    container_name: 'hovi-web_nginx'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
