version: '3.5'

services:
  hovi-web_dev:
    build: ../
    container_name: 'hovi-web_dev'
    command: npm run start
    ports:
      - 8000:8000
    volumes:
      - ../src:/usr/src/app/src
      - ../mock:/usr/src/app/mock
